-- This file was generated by the Reassembly Web Development Kit (RWDK)
-- RWDK is an independent project and in no way affiliated with Anisoptera Games.
-- RWDK was written by TTFTCUTS

{
	970 = {
		name="Grand Valorkyn",
		playable=2,
		start="970_Phage",
		
		explosionColor0=0x88ee22,--green
		explosionColor1=0x541434,--purple
		
		color0=0x88ee22,--green
		color1=0xaaaa88,--tan
		
		aiflags=FORGIVING|WANDER|RECKLESS|METAMORPHOSIS|BAD_AIM|FLOCKING,
	},

}
